apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    #https://argoproj.github.io/argo-cd/user-guide/sync-options/#no-prune-resources
    # argocd.argoproj.io/sync-options: Prune=false
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    chart: istio-base
    repoURL: https://github.com/dubass83/learn-terraform-provision-aks-cluster
    path: apps/istio/files/charts/base
    targetRevision: HEAD
    # helm specific config
    helm:
      # Release name override (defaults to application name)
      releaseName: istio-base


  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    # syncOptions:     # Sync options which modifies sync behavior
    # - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')

  # # Ignore differences at the specified json pointers
  # ignoreDifferences:
  # - group: monitoring.coreos.com
  #   kind: Alertmanager
  #   jsonPointers:
  #   - /spec/storage/volumeClaimTemplate/selector
  # - group: monitoring.coreos.com
  #   kind: Prometheus
  #   jsonPointers:
  #   - /spec/storage/volumeClaimTemplate/selector