---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-apps
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: apps/system
    repoURL: https://github.com/dubass83/learn-terraform-provision-aks-cluster
    # targetRevision:
    # helm:
    #   valueFiles:
    #     - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true